"use client";

import {
  IconTarget,
  IconTrophy,
  IconStar,
  IconMedal,
  IconAward,
  IconFlame,
  IconBolt,
  IconRocket,
  IconFlag,
  IconFlagFilled,
  IconChecklist,
  IconCircleCheck,
  IconThumbUp,
  IconBriefcase,
  IconPresentation,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconBuildingSkyscraper,
  IconTie,
  IconClipboard,
  IconCalendar,
  IconClock,
  IconMail,
  IconPhone,
  IconUsers,
  IconUserCircle,
  IconCash,
  IconCoin,
  IconPigMoney,
  IconWallet,
  IconCreditCard,
  IconReceipt,
  IconReportMoney,
  IconTrendingUp,
  IconBuildingBank,
  IconDiamond,
  IconHeartbeat,
  IconHeart,
  IconYoga,
  IconRun,
  IconBike,
  IconSwimming,
  IconApple,
  IconSalad,
  IconMoon,
  IconSun,
  IconDroplet,
  IconStretching,
  IconBook,
  IconBooks,
  IconSchool,
  IconCertificate,
  IconBulb,
  IconBrain,
  IconMicroscope,
  IconNotebook,
  IconPencil,
  IconLanguage,
  IconMath,
  IconAtom,
  IconPalette,
  IconBrush,
  IconMusic,
  IconCamera,
  IconPhoto,
  IconMovie,
  IconMicrophone,
  IconPiano,
  IconGuitarPick,
  IconDeviceTv,
  IconWriting,
  IconVinyl,
  IconCode,
  IconDevices,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconBrandGithub,
  IconDatabase,
  IconCloud,
  IconWifi,
  IconCpu,
  IconTerminal,
  IconApi,
  IconBug,
  IconPlane,
  IconMap,
  IconCompass,
  IconMountain,
  IconTree,
  IconLeaf,
  IconFlower,
  IconSunrise,
  IconBeach,
  IconCar,
  IconWorld,
  IconTent,
  IconHome,
  IconFriends,
  IconMoodSmile,
  IconGift,
  IconBabyCarriage,
  IconDog,
  IconCat,
  IconArmchair,
  IconCoffee,
  IconToolsKitchen,
  IconSoup,
  IconCircle,
  IconSquare,
  IconTriangle,
  IconHexagon,
  IconPoint,
  IconBookmark,
  IconPin,
  IconTag,
  IconHash,
  IconAt,
  IconLink,
  IconLock,
  IconShield,
  IconEye,
  IconSearch,
  IconSettings,
} from "@tabler/icons-react";
import { type ComponentType } from "react";
import { getIconColorValue } from "./iconPickerData";

// Static map from icon name to component
const ICON_MAP: Record<string, ComponentType<{ size?: string | number; className?: string; style?: React.CSSProperties }>> = {
  IconTarget,
  IconTrophy,
  IconStar,
  IconMedal,
  IconAward,
  IconFlame,
  IconBolt,
  IconRocket,
  IconFlag,
  IconFlagFilled,
  IconChecklist,
  IconCircleCheck,
  IconThumbUp,
  IconBriefcase,
  IconPresentation,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconBuildingSkyscraper,
  IconTie,
  IconClipboard,
  IconCalendar,
  IconClock,
  IconMail,
  IconPhone,
  IconUsers,
  IconUserCircle,
  IconCash,
  IconCoin,
  IconPigMoney,
  IconWallet,
  IconCreditCard,
  IconReceipt,
  IconReportMoney,
  IconTrendingUp,
  IconBuildingBank,
  IconDiamond,
  IconHeartbeat,
  IconHeart,
  IconYoga,
  IconRun,
  IconBike,
  IconSwimming,
  IconApple,
  IconSalad,
  IconMoon,
  IconSun,
  IconDroplet,
  IconStretching,
  IconBook,
  IconBooks,
  IconSchool,
  IconCertificate,
  IconBulb,
  IconBrain,
  IconMicroscope,
  IconNotebook,
  IconPencil,
  IconLanguage,
  IconMath,
  IconAtom,
  IconPalette,
  IconBrush,
  IconMusic,
  IconCamera,
  IconPhoto,
  IconMovie,
  IconMicrophone,
  IconPiano,
  IconGuitarPick,
  IconDeviceTv,
  IconWriting,
  IconVinyl,
  IconCode,
  IconDevices,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconBrandGithub,
  IconDatabase,
  IconCloud,
  IconWifi,
  IconCpu,
  IconTerminal,
  IconApi,
  IconBug,
  IconPlane,
  IconMap,
  IconCompass,
  IconMountain,
  IconTree,
  IconLeaf,
  IconFlower,
  IconSunrise,
  IconBeach,
  IconCar,
  IconWorld,
  IconTent,
  IconHome,
  IconFriends,
  IconMoodSmile,
  IconGift,
  IconBabyCarriage,
  IconDog,
  IconCat,
  IconArmchair,
  IconCoffee,
  IconToolsKitchen,
  IconSoup,
  IconCircle,
  IconSquare,
  IconTriangle,
  IconHexagon,
  IconPoint,
  IconBookmark,
  IconPin,
  IconTag,
  IconHash,
  IconAt,
  IconLink,
  IconLock,
  IconShield,
  IconEye,
  IconSearch,
  IconSettings,
};

export { ICON_MAP };

interface GoalIconProps {
  icon: string | null | undefined;
  iconColor: string | null | undefined;
  size?: number;
  className?: string;
}

export function GoalIcon({ icon, iconColor, size = 24, className }: GoalIconProps) {
  if (!icon) {
    return <IconTarget size={size} className={className ?? "text-text-muted"} />;
  }

  if (icon.startsWith("emoji:")) {
    const emoji = icon.slice(6);
    return (
      <span style={{ fontSize: size * 0.85, lineHeight: 1 }} className={className}>
        {emoji}
      </span>
    );
  }

  if (icon.startsWith("tabler:")) {
    const iconName = icon.slice(7);
    const IconComponent = ICON_MAP[iconName];
    if (IconComponent) {
      return (
        <IconComponent
          size={size}
          className={className}
          style={{ color: getIconColorValue(iconColor) }}
        />
      );
    }
  }

  // Fallback
  return <IconTarget size={size} className={className ?? "text-text-muted"} />;
}
