import {
  IconAddressBook,
  IconBell,
  IconBolt,
  IconBook,
  IconBrandChrome,
  IconBrandGithub,
  IconBrandNotion,
  IconBrandSlack,
  IconBrandWhatsapp,
  IconBuildingSkyscraper,
  IconCalendarWeek,
  IconChartBar,
  IconChecklist,
  IconCircles,
  IconClock,
  IconDatabase,
  IconDeviceMobile,
  IconFlame,
  IconFolders,
  IconInbox,
  IconKey,
  IconLayoutNavbar,
  IconMicrophone,
  IconNotebook,
  IconPlayerPlay,
  IconPlug,
  IconRepeat,
  IconRobot,
  IconRobotFace,
  IconRocket,
  IconSettings,
  IconStack2,
  IconSunrise,
  IconTarget,
  IconTargetArrow,
  IconTerminal2,
  IconUsers,
} from "@tabler/icons-react";
import type { ElementType } from "react";

/**
 * Icons a docs page may name in its `icon:` frontmatter. Add here when a new
 * page needs one; unknown names render no icon rather than breaking the build.
 */
export const DOC_ICONS: Record<string, ElementType> = {
  IconAddressBook,
  IconBell,
  IconBolt,
  IconBook,
  IconBrandChrome,
  IconBrandGithub,
  IconBrandNotion,
  IconBrandSlack,
  IconBrandWhatsapp,
  IconBuildingSkyscraper,
  IconCalendarWeek,
  IconChartBar,
  IconChecklist,
  IconCircles,
  IconClock,
  IconDatabase,
  IconDeviceMobile,
  IconFlame,
  IconFolders,
  IconInbox,
  IconKey,
  IconLayoutNavbar,
  IconMicrophone,
  IconNotebook,
  IconPlayerPlay,
  IconPlug,
  IconRepeat,
  IconRobot,
  IconRobotFace,
  IconRocket,
  IconSettings,
  IconStack2,
  IconSunrise,
  IconTarget,
  IconTargetArrow,
  IconTerminal2,
  IconUsers,
};

export function resolveDocIcon(name: string | undefined): ElementType | undefined {
  if (!name) return undefined;
  return DOC_ICONS[name];
}
