/**
 * "Last updated" dates for docs pages.
 *
 * Source of truth is git, but the build machine's clone is usually shallow
 * (Vercel fetches ~10 commits), and in a shallow clone `git log -1 -- file`
 * reports the shallow boundary commit for any file older than the fetch
 * depth — a wrong, too-recent date. So:
 *
 *   1. `content/docs/_last-updated.json` holds a committed map of
 *      file path → ISO date, regenerated by the pre-commit hook whenever a
 *      docs page is staged (`scripts/docs-last-updated.ts`).
 *   2. At render time we still ask git, and prefer its answer only when the
 *      commit it names is not a shallow boundary.
 *
 * Both pieces are tolerant: no git, no map, or a page missing from the map
 * simply yields `null` and the page renders without a date.
 */
import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";

export const LAST_UPDATED_FILE = path.join(process.cwd(), "content/docs/_last-updated.json");

export type LastUpdatedMap = Record<string, string>;

export function readLastUpdatedMap(): LastUpdatedMap {
  try {
    return JSON.parse(fs.readFileSync(LAST_UPDATED_FILE, "utf-8")) as LastUpdatedMap;
  } catch {
    return {};
  }
}

function git(args: string[]): string | null {
  try {
    return execFileSync("git", args, {
      cwd: process.cwd(),
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 5000,
    }).trim();
  } catch {
    return null;
  }
}

let shallowBoundary: Set<string> | null = null;

function shallowCommits(): Set<string> {
  if (shallowBoundary) return shallowBoundary;
  shallowBoundary = new Set();
  const gitDir = git(["rev-parse", "--git-dir"]);
  if (gitDir) {
    try {
      const shallowFile = path.resolve(process.cwd(), gitDir, "shallow");
      for (const line of fs.readFileSync(shallowFile, "utf-8").split("\n")) {
        if (line.trim()) shallowBoundary.add(line.trim());
      }
    } catch {
      // Not a shallow clone.
    }
  }
  return shallowBoundary;
}

/** Commit date of the last commit touching `filePath`, or null when git cannot say reliably. */
export function gitLastUpdated(filePath: string): string | null {
  const out = git(["log", "-1", "--format=%H %cI", "--", filePath]);
  if (!out) return null;
  const [sha, date] = out.split(" ");
  if (!sha || !date) return null;
  if (shallowCommits().has(sha)) return null;
  return date;
}

/**
 * Best available date for a page: git when trustworthy, otherwise the
 * committed map. Returns an ISO string or null.
 */
export function getLastUpdated(filePath: string, map: LastUpdatedMap = readLastUpdatedMap()): string | null {
  const fromGit = gitLastUpdated(filePath);
  const fromMap = map[filePath] ?? null;
  if (fromGit && fromMap) return fromGit > fromMap ? fromGit : fromMap;
  return fromGit ?? fromMap;
}
