import Layout from "~/app/_components/layout/Layout";
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} h-full`}>
      <body className="h-full bg-gradient-to-b from-[#111111] to-[#212121] ">
        <Layout>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </Layout>
      </body>
    </html>
  );
}
